version: "3.8"

services:
  xet-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT:-8080}:80
    environment:
      DB_SERVER: ${DB_SERVER:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-xet}
      DB_PASSWORD: ${DB_PASSWORD:-xet}
      DB_DATABASE: ${DB_DATABASE:-xet}
    volumes:
      - .:/var/www/html
    depends_on:
      - xet-db
    networks:
      - xet-network

  xet-db:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-xet}
      MYSQL_USER: ${MYSQL_USER:-xet}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-xet}
    ports:
      - ${DB_PORT:-3306}:3306
    networks:
      - xet-network
    volumes:
      - ./init/create_user.sh:/docker-entrypoint-initdb.d/create_user.sh
networks:
  xet-network:
    driver: bridge
